In [ ]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
list = [10,20,30]
arr  = np.array(list)


pd.Series(list,index = labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
student = {
    "name": ["Rahul", "Aman", "Priya", "Neha", "Karan"],
    "age": [21, 22, 20, 21, 23],
    "marks": [85, 90, 78, 92, 88],
    "city": ["Delhi", "Mumbai", "Pune", "Chennai", "Ghaziabad"],
    "grade": ["A", "A+", "B", "A+", "A"]
}

d1 = pd.DataFrame(student)
d1

    name  age  marks       city grade
0  Rahul   21     85      Delhi     A
1   Aman   22     90     Mumbai    A+
2  Priya   20     78       Pune     B
3   Neha   21     92    Chennai    A+
4  Karan   23     88  Ghaziabad     A

In [ ]:
d1["Designation"]  = ["A","B","C","D","E"]
d1
#adding a row

    name  age  marks       city grade Designation
0  Rahul   21     85      Delhi     A           A
1   Aman   22     90     Mumbai    A+           B
2  Priya   20     78       Pune     B           C
3   Neha   21     92    Chennai    A+           D
4  Karan   23     88  Ghaziabad     A           E

In [ ]:
d1.drop('city',axis = 1,inplace= True)
d1
#deleting a row permamnent

    name  age  marks grade
0  Rahul   21     85     A
1   Aman   22     90    A+
2  Priya   20     78     B
3   Neha   21     92    A+
4  Karan   23     88     A

In [ ]:
d1.loc[[0,1]] #selecting a index

    name  age  marks grade
0  Rahul   21     85     A
1   Aman   22     90    A+

In [ ]:
d1.loc[[0,1]][["name","age"]]

    name  age
0  Rahul   21
1   Aman   22

In [ ]:
d1[d1["age"] > 21]
#condition selection

    name  age  marks grade
1   Aman   22     90    A+
4  Karan   23     88     A

In [ ]:
#d1[(d1["name"] == "Karan") & (d1[d1["grade"] == "A")]
#double condition

In [ ]:
import numpy as np
import pandas as pd

data = {
    "name": ["Rahul", "Aman", np.nan, "Neha", "Karan"],
    "age": [21, np.nan, 20, 21, 23],
    "marks": [85, 90, np.nan, 92, 88],
    "city": ["Delhi", np.nan, "Pune", "Chennai", "Ghaziabad"],
    "grade": ["A", "A+", np.nan, "A+", "A"]
}

d1 = pd.DataFrame(data)
d1

    name   age  marks       city grade
0  Rahul  21.0   85.0      Delhi     A
1   Aman   NaN   90.0        NaN    A+
2    NaN  20.0    NaN       Pune   NaN
3   Neha  21.0   92.0    Chennai    A+
4  Karan  23.0   88.0  Ghaziabad     A

In [ ]:
d1.isna()

    name    age  marks   city  grade
0  False  False  False  False  False
1  False   True  False   True  False
2   True  False   True  False   True
3  False  False  False  False  False
4  False  False  False  False  False

In [ ]:
d1.isna().any()
#checking if a columns have a null or not

name     True
age      True
marks    True
city     True
grade    True
dtype: bool

In [ ]:
d1.dropna()

    name   age  marks       city grade
0  Rahul  21.0   85.0      Delhi     A
3   Neha  21.0   92.0    Chennai    A+
4  Karan  23.0   88.0  Ghaziabad     A

In [ ]:
d1.dropna(thresh = 4)
#no of non null values = thresh

    name   age  marks       city grade
0  Rahul  21.0   85.0      Delhi     A
3   Neha  21.0   92.0    Chennai    A+
4  Karan  23.0   88.0  Ghaziabad     A

In [ ]:
d1.fillna(5)

    name   age  marks       city grade
0  Rahul  21.0   85.0      Delhi     A
1   Aman   5.0   90.0          5    A+
2      5  20.0    5.0       Pune     5
3   Neha  21.0   92.0    Chennai    A+
4  Karan  23.0   88.0  Ghaziabad     A